### ISSUE TITLE
Remix: overlap of outDir & publicDir caused a warning.

### ISSUE THREAD

**Issue by EarthlingDavey** [manawiki/repay#13]
Running `yarn build:remix` gives the following warning.

(!) The public directory feature may not work correctly. outDir /home/node/public/build and publicDir /home/node/public are not separate folders.

**Comment by xHomu** [comment]
Sorry I haven't catch up with this so far, this bug will be addressed by an upstream update from the Remix Team:

https://twitter.com/markdalgleish/status/1727141990641652137

https://github.com/remix-run/remix/pull/8077
