### ISSUE TITLE
Repo is not working for me

### ISSUE THREAD

**Issue by fzsf163** [manawiki/repay#16]
I cloned the repo and ```yarn install``` then ```yarn dev``` . This error shows up.

![Screenshot 2024-01-30 174851](https://github.com/manawiki/repay/assets/86884235/2b56f094-9b44-4e18-8600-620c8aee5866)

**Comment by xHomu** [comment]
You need to fill in your env variables, copy this over as .env:

https://github.com/manawiki/repay/blob/main/.env.example


* PAYLOAD_SECRET:  a random secret, generate with `openssl rand -hex 32` or https://1password.com/password-generator/
* MONGODB_URI: URI to Your MongoDB database, if you don't have one available, you can create one over at Mongo Atlas https://www.mongodb.com/atlas/database
