### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by kwabe007** [manawiki/repay#20]
Hi, I assume it's intended for this template to be free to use for most purposes so it would be good to add a license just to make it explicit.

**Comment by xHomu** [comment]
Ops! Yes, will get right to it tomorrow!

**Comment by xHomu** [comment]
Also, feel free to rec a license in a PR! Would probably just do MIT unless
there's a better suggestion.

**Comment by kwabe007** [comment]
MIT will work fine! It's what most people would expect.
